[build]
builder = "nodejs"
buildCmd = "NODE_OPTIONS=\"--max-old-space-size=512\" pnpm install --frozen-lockfile --shamefully-hoist && pnpm run build"

[start]
startCmd = "node packages/api/dist/index.js"

[phases.setup]
nixPkgs = ["nodejs_20"]
