[build]
builder = "nodejs"
buildCmd = "npm install --legacy-peer-deps"

[start]
startCmd = "node packages/api/dist/index.js"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g npm@latest"
